# Generated by Django 4.2.2 on 2023-06-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgets',
            options={'verbose_name': 'Budgets', 'verbose_name_plural': 'Budgets'},
        ),
    ]
